config/routes.rb
Rails.application.routes.draw do
  resources :inventarios

  root 'inventarios#index'

end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventarios_controller.rb
class InventariosController < ApplicationController
  before_action :set_inventario, only: [:show, :edit, :update, :destroy]

  # GET /inventarios
  # GET /inventarios.json
  def index
    @inventarios = Inventario.all
    @inventario = Inventario.new
  end

  # GET /inventarios/1
  # GET /inventarios/1.json
  def show
  end

  # GET /inventarios/new
  def new
    @inventario = Inventario.new
  end

  # GET /inventarios/1/edit
  def edit
  end

  # POST /inventarios
  # POST /inventarios.json
  def create
    @inventario = Inventario.new(inventario_params)

    respond_to do |format|
      if @inventario.save
        format.html { redirect_to action: "index", notice: 'Inventario was successfully created.' }
        format.json { render :show, status: :created, location: @inventario }
      else
        format.html { render :new }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventarios/1
  # PATCH/PUT /inventarios/1.json
  def update
    respond_to do |format|
      if @inventario.update(inventario_params)
        format.html { redirect_to @inventario, notice: 'Inventario was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventario }
      else
        format.html { render :edit }
        format.json { render json: @inventario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventarios/1
  # DELETE /inventarios/1.json
  def destroy
    @inventario.destroy
    respond_to do |format|
      format.html { redirect_to inventarios_url, notice: 'Inventario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventario
      @inventario = Inventario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventario_params
      params.require(:inventario).permit(:fecha, :producto, :precio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/views/inventarios/_form.html.erb
<%= form_for(@inventario, remote: true) do |f| %>
  <% if @inventario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventario.errors.count, "error") %> prohibited this inventario from being saved:</h2>

      <ul>
      <% @inventario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_field :fecha %>
  </div>
  <div class="field">
    <%= f.label :producto %><br>
    <%= f.text_field :producto %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventarios/edit.html.erb
<h1>Editing Inventario</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventario %> |
<%= link_to 'Back', inventarios_path %>

app/views/inventarios/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Formulario</h1>
<br>
<%= render 'form' %>
<br>

<h1>Lista de Productos</h1>
<br>
<table>
  <thead>
    <tr>
      <th>Fecha de vencimiento</th>
      <th>Producto</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventarios.each do |inventario| %>
      <tr>
        <td><%= inventario.fecha %></td>
        <td><%= inventario.producto %></td>
        <td><%= inventario.precio %></td>
        <td><%= link_to 'ver', inventario %></td>
        <td><%= link_to 'Editar', edit_inventario_path(inventario) %></td>
        <td><%= link_to 'Eliminar', inventario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/inventarios/new.html.erb
<h1>New Inventario</h1>

<%= render 'form' %>

<%= link_to 'Back', inventarios_path %>

app/views/inventarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @inventario.fecha %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @inventario.producto %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @inventario.precio %>
</p>

<%= link_to 'Edit', edit_inventario_path(@inventario) %> |
<%= link_to 'Back', inventarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventarioReact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>